-- 1. Total Revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue 
FROM customer 
GROUP BY gender

-- 2. Which customers spent more than the average purchase amount even after using a discount?
SELECT customer_id, gender, purchase_amount 
FROM customer 
WHERE discount_applied in ('Yes') AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)

-- 3. Top 5 products having highest average review rating?
SELECT item_purchased, category, ROUND(AVG(review_rating)::numeric,2) AS average_rating
FROM customer
GROUP BY item_purchased, category
ORDER BY AVG(review_rating) DESC LIMIT 5

-- 4. Comparing Average Purchase Amounts Between Standard and Express Shipping.
SELECT shipping_type,
ROUND(AVG(purchase_amount),2) AS average_purchase_amount
FROM customer 
WHERE shipping_type IN('Express','Standard')
GROUP BY shipping_type

-- 5. Comparing average spend and total revenue between subscribers and non-subscribers (Who spends more)
SELECT subscription_status,
COUNT(customer_id) AS total_customer,
ROUND(AVG(purchase_amount),2) AS average_purchase_amount,
ROUND(SUM(purchase_amount),2) AS total_purchase_amount
FROM customer
GROUP BY subscription_status

--6. Top 5 product with highest percentage of purchases with discounts applied.(Product that has highest discount applied)
SELECT item_purchased,
ROUND(100*
	SUM(CASE
		WHEN discount_applied = 'Yes' THEN 1 ELSE 0
		END)/COUNT(*),2) AS discount_applied_percentage
FROM customer
GROUP BY item_purchased 
ORDER BY discount_applied_percentage DESC
LIMIT 5
