-- 1. Total Revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue 
FROM customer 
GROUP BY gender

-- 2. Which customers spent more than the average purchase amount even after using a discount?
SELECT customer_id, gender, purchase_amount 
FROM customer 
WHERE discount_applied in ('Yes') AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)

-- 3. Top 5 products having highest average review rating?
SELECT item_purchased, category, ROUND(AVG(review_rating)::numeric,2) AS average_rating
FROM customer
GROUP BY item_purchased, category
ORDER BY AVG(review_rating) DESC LIMIT 5

-- 4. Comparing Average Purchase Amounts Between Standard and Express Shipping.
SELECT shipping_type,
ROUND(AVG(purchase_amount),2) AS average_purchase_amount
FROM customer 
WHERE shipping_type IN('Express','Standard')
GROUP BY shipping_type

-- 5. Comparing average spend and total revenue between subscribers and non-subscribers (Who spends more)
SELECT subscription_status,
COUNT(customer_id) AS total_customer,
ROUND(AVG(purchase_amount),2) AS average_purchase_amount,
ROUND(SUM(purchase_amount),2) AS total_purchase_amount
FROM customer
GROUP BY subscription_status

--6. Top 5 product with highest percentage of purchases with discounts applied.(Product that has highest discount applied)
SELECT item_purchased,
ROUND(100*
	SUM(CASE
		WHEN discount_applied = 'Yes' THEN 1 ELSE 0
		END)/COUNT(*),2) AS discount_applied_percentage
FROM customer
GROUP BY item_purchased 
ORDER BY discount_applied_percentage DESC
LIMIT 5

--7. Segment the customer into different segments (New, returning, Loyal) with total number falling in each segment
WITH customer_type AS(
	SELECT customer_id,
	CASE
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
	END AS customer_segment
	FROM customer
)

SELECT customer_segment,
COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment

--8. Top 3 most purchased products within each category
WITH top_products AS(
	SELECT category,
	item_purchased,
	COUNT(item_purchased) AS total_purchase,
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS product_rank
	FROM customer	
	GROUP BY category,item_purchased
)

SELECT * FROM top_products WHERE product_rank <= 3

-- 9. Are customers who are repeat buyers(more than 5 prev. purchase) also likely to subscribe?
SELECT subscription_status, 
COUNT(customer_id) AS repeat_buyers_count 
FROM customer 
WHERE previous_purchases > 5 
GROUP BY subscription_status

-- 10. Revenue By Age-Group
SELECT age_group,
ROUND(SUM(purchase_amount),2) AS total_purchase,
ROUND(AVG(purchase_amount),2) AS average_purchase
FROM customer
GROUP BY age_group
